apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: databases
spec:
  encryptedData:
    password: AgBClkLKE5tnygL8ihvDJqNpCAdscryni8DV6CpFDD26UY4szbsUC1byXZ1KNkV/08J9Nxj9jfLXl/ZYG8ZsSqN0yacfffO3mNVR+6Wuydlea6Lu2iZthV8F0klgSFSTwgBGMoMFAPNJ0P1SOhpGI4+vqyodvSEF454lxd+H6eFLO71xBgxzSE0z9FAGFpluQe8Z1E8i0qSwE8Rx7xbe5GPE7AhI5rW1x3fUaMy+JS2h7qvEJUQ2fD7sufnUvmbiQSMaKms31l7tFXMW1Z8uS2cqO5Fa/u7C1Qx2Pn2rVLcnqXND7F7tyY1ydZJYsVz6wR7XwBE+mlst6OSN8NJ9N7UZmmp35D4f5K4ho6VKKtyjs593K/x1LR/nKBHI7P9geJBf8LJnrnZY39z9dw5bq5CZZVOiAjuyIbugQ2AKpVdtOMsL4tJ2ZcAww9dSlgtXRXwXXvRmp7TWadM6VqU4A272Sde4EJTKDd+GOCYVrG8DuPd1SRWq/VwNe1cluzR1JbKCL36FC7aW1VHt1s30vKRMTcNcCO6Q036Mgygx2vTQjnl4VjOq4jNZP1pktvWwHRomWU1MS60gYXIneEtvAjiY4ifwB7fjlsLQjdz3F34qR2rOvI59whQVvEhimU5vAootQwe5f3YYbESaY52RMbNeMEeNQLl6hHJvMlU2MGvgWF3pa5d77fDM1Buhw+AVzNCz52YoFdN5vDQ6ghnH9wNog0mT1Fs=
  template:
    metadata:
      name: redis-credentials
      namespace: databases
