apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minttracker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/vimleshkpandey/platform-gitops
      targetRevision: HEAD
      path: charts/springboot-app
      helm:
        releaseName: minttracker
        valueFiles:
          - $appvalues/applications/minttracker/values.yaml
    - repoURL: https://github.com/vimleshkpandey/platform-gitops
      targetRevision: HEAD
      ref: appvalues
    - repoURL: https://github.com/vimleshkpandey/platform-gitops
      targetRevision: HEAD
      path: applications/minttracker/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
