---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: redis-credentials
  namespace: databases
spec:
  encryptedData:
    password: AgA2nM+YtrxvTqyYvZMeM3A7MUCPQwsf09+TA4e+ijY5mN0BWHG1ZJOLunR4iUomh+fRSclYML+5AuzqxwRHZaC/ZHXAdrV+ec+SDdBGHThcf2NXSg+aFUCdLfv2Vzy9DKy87FCDBAi2zaz3tSaWjOGjeGX/CsLZMWJcUb+QloyW3lwd9UTZRd8appBPoSV0HjjosPHlmaaUfZ17ebE0dfC8uBxJYpAfvw3yHXVJr+IVDBAI678ywvDal7t74Ra0oPr+M7OZLooTH4Gp24E1P4ACZLy7I9yUtSlsvfoBIRzNm5NkGO9Y0EvgDg2UqKU2le3rLaCpC+rOKS5s0sEUk6uD8CyRbH6NPIN0atlA13G9ibGnAYhJ6mVYxWdIppBv7dDw17lAPGb7CJwlTLS9D5PGisB64VKw52e0iyeDgI3hzjLtfsdhGdy6+A5uvRBWSKju3mBUE4PF83CAfWaEvHhAhJ9qvKBOJCqrE04V4K3I4xoXytlZT/i5IzGO2+i93f0v0dPox79A36PPh9uwiVibrd8DG4olYFKtTQwVUiF9N+Z4GK+NBNKbzGRbLa8PNL465k/eOYj80wYzEGJtyLUSOfKWFW1b3brGJGojmOoHVvoEENypMO5F/K560+lbBXGfwcnr1dfTuyVFaSGtPl53EVJ9IDNXxP4DQM9+m8N91Wb5zXDQstaaWoao4hxk2gUQssSEzDKoKT0ywrgMtC+J6ivswQbgI5G0UEgGelm6cg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: redis-credentials
      namespace: databases
