---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgresql-credentials
  namespace: databases
spec:
  encryptedData:
    password: AgBVQtC3+aLNiZEyqoxewZqbPDjgiFRI99DgmA8nxDABh+Q5VEkQHoAYMd+UmWbqKNW4HNDMLRKKY5rLRVDGK4WSyzEnpfriQ1KoWeLum10aapH/lzVFc4DtXB09iYiJzrm8hxmFqjBVy7b2+5eHYs9+Vc4Zu5elg1jojFDYZ3pkK0VMJxk6ASkG8zznOa3j+69eIxVlls3Uy/VIyUKvVSC9Ill6hQ4T58uRikOlJYc3pEboaws/7kBxOVI5TX9IOz++ow29ogeDQ6cTba3/s39mNIMsnmXvoRVsmccFdck3AHNWKXc+XmtQ/vDFZA062BbMurZB4z9JXERlIYgB+eUF/4EZXKYd1H92LRba2GQbYhWxc7SkAlQOHp6JcO1apdKDKVm1BCPFJtBZw0qoeBN6oDdVTus5SWd+cQPEAMSVwp+2+I+L3X105ZoT7r7CPAhE1BCO5gUklKfsQ/YkvojOWvsh5XMq0WHucCSv7XLQ7cTt/O88kQSJVzsYc6jv6jqnDyFo6t46L5cyL5Y8XeGObKlzKlOU3iONuz3gtCGn1dqEiScb2ZYaOD/BS+rJ6EYN+QFLqFGm9QeBa03vSj4pC75AsfVxM6bf5SCG6bmHSozmNLi32A6e9h+Uyb53XMNfvsBdu4llIz/MqHYQ4Egv9IW6CRZapDfw09wk4oKXpjwCbt3EGsuYmpbhNA7FcP21cxNtFN++SPi7606w11/JcnawFaGbyrwGhpfYjSLyjA==
    postgres-password: AgBIvuBo/K3fa/KCq5JiG+SuaHL7lsnGMSkp1IjoxiccqzzCweUOrZIcSwU3MtSkQcQd3vDf+YXQqvLHg6JaHEa3BuyPAyTyQrJ5km1ne63wIOmVGtXTpmw0GtTNoHD4m/AWnbpuiaeHkG38BvMgW8rkYAkaRkcYPJRWC/KBqTkuXbAqKYNRt1vAkvtYmzfieDgbqQ8/VA6l7HHHK+kIOnjT8swG/oggX22JnEiILMiYHu5dUtHv4lbVP9ocTAoVtgtFG98Sx/3GZTwKlTjWoMWk49dqUxIHsKInlm9+nxgkRt9PVfUYuKDkXNRV5nEXxvj+sl/MXIz9ZOZymantuj7wD/Q7gIfM0giTAWvZhegkncdMo1W8mow1+2xCeVVECBXqFZ+9QW0/ElHAMlLotKsW+PgRgc1sQr/0FWuVCAN5dMJA3qGH6pTkmyMWk59KP51incMUgbHdh6AESpkexyyDKzoqw+2yFG4eBPP4yd5ZUZo2T1xKzR5LiAAfL4wi8IXLL0zYp8AS9sfDGdjxsrDfneDppzdkh6A3YhzJvdP9vOzgtJYNKS+f9vU5aKAfs+ZGlJ0x71v4s1JAkSiU5UmacYjgrTaaIi1Be+V7tuXCJT6cLr9pCltgZdWrycJlxLgd0bsle4m+ghif/ap/X1cBXFEzlgzVCx/MJZvp/QXKQGwFRXg0KPh7Rp5bQM8UyQ6obOyZHM3T1il9AMR18aQ4qLlQcvT+/UKwY7MFyPcyCQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postgresql-credentials
      namespace: databases
