postgresql:
  auth:
    existingSecret: postgresql-credentials
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
    database: appdb

  primary:
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1500Mi

    persistence:
      enabled: true
      storageClass: local-path
      size: 20Gi

    podSecurityContext:
      runAsNonRoot: true
      fsGroup: 1001

    containerSecurityContext:
      runAsNonRoot: true
      runAsUser: 1001

    initdb:
      scripts:
        init.sql: |
          CREATE DATABASE customerdb;
          CREATE DATABASE paymentdb;
          CREATE DATABASE notificationdb;

  metrics:
    enabled: false
