apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: applications
spec:
  encryptedData:
    .dockerconfigjson: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: applications
    type: kubernetes.io/dockerconfigjson
