---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ghcr-pull-secret
  namespace: applications
spec:
  encryptedData:
    .dockerconfigjson: AgAaXCO4c2RW5+OzXmGcPNjeUx0nLiTQjRQkC7mx8rqL0zLe2vK2x185H6AnqjQ1AxE79YV5cpYpESr7IM/hq8qTtQsfw3lpl8iTMzeg3U35YU3kZZYvumoT1sUbQtEB9mcgatyKA5YDB3CL7cCtIi25XqOhTLnMp7dLmBge5yLA0jrABCXgBpepFXzeublJW0tO8yjpos+8wkblDqej6en7e5kSyrxmmuccmLF1Hug6n35CQIq58I9maPjsIasq6awHswtWIQU9hr+uyKbzSv7vIzeo3cPjJvSI/kO0X2circZdHe6RtZM10sk5d/7dBeUkZ+/TezZPF6Es4u4YlZ1oB2oiEkaHG+o2NWyVvZYpVIx4idUAbeC5nJYm1m777tzxfPDKfaMwFvvaGm3LIZ371U3IMlP7EKJnD3N68lJEjQ3vY1+7gaZ+nDPicF5tFpptiSUM/LooVGZ/E74jl8uAY6B5M+EN/dpeRVXKGbhWjYB8tR2aJ0XMvx0Uqb9Blxqir+pcrK7jXTuWj32Xt6KIwWvVay91QhGbBYmNPQTPqTyn2c1XV0E0JYx8HuyR1Cghz/mdtx1HVDC8TSndzXx/mVULer8WsPIhmx5FG4N8eiecMHpNDvlZv2IQNNIjctXH/7qoIQfl73IgMu+a7eQ81Qe/tZOYPGOuBv+FR9CjJHHBa3EPWQIG8ExEg07luqiXrET+MQ6QOVjZdX65e55io/OZWUudrtJwkEG4xDI8xe4Cf91PMBbbWCW+4r2g21nc2NiUEYuIB8F7aO6Ix6BcY9Ahxtz5bNg7Lr3pFS+rm0xAVZgETE2MVDSKCH87c+K7A4Qw3S3SyCN+fnCrM+mo+TSo2JXan3u1W4y9gWGIYjmX3v9KbuuFUcvDr+nq88JYWSA3VmOlwbA4zHdFCIm1FX+omDu6+KaOQcV4tRlGhgZQ8QO6rHkfueYQZOtjXg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ghcr-pull-secret
      namespace: applications
    type: kubernetes.io/dockerconfigjson
